//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGuidance.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGetGuidance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Guidance.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composed {0} recipe(s)..
        /// </summary>
        public static string ComposedRecipes {
            get {
                return ResourceManager.GetString("ComposedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composing Recipes....
        /// </summary>
        public static string ComposingRecipes {
            get {
                return ResourceManager.GetString("ComposingRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string ErrorDetail {
            get {
                return ResourceManager.GetString("ErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more info, please check your Event Viewer..
        /// </summary>
        public static string EventViewer {
            get {
                return ResourceManager.GetString("EventViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception was thrown with the following message:
        ///
        ///&quot;{0}&quot;.
        /// </summary>
        public static string ExceptionInfo {
            get {
                return ResourceManager.GetString("ExceptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed..
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Recipe &quot;{0}&quot;..
        /// </summary>
        public static string FinishingRecipe {
            get {
                return ResourceManager.GetString("FinishingRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For help with this issue, please right-click the list and save the log. Sending us the log file will make it easier to track down what exactly went wrong during execution..
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  • Message: [ {0} ], LogLevel: [ {1} ].
        /// </summary>
        public static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to •   •   •   •   •   •   •.
        /// </summary>
        public static string LogSeperator {
            get {
                return ResourceManager.GetString("LogSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipes have been found..
        /// </summary>
        public static string NoRecipesFound {
            get {
                return ResourceManager.GetString("NoRecipesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not found in any of the subfolders of &quot;{1}&quot;..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify or supply the correct input for &quot;{0}&quot;....
        /// </summary>
        public static string PleaseSupply {
            get {
                return ResourceManager.GetString("PleaseSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Guidance has encountered an unrecoverable error and cannot continue..
        /// </summary>
        public static string RunFailed {
            get {
                return ResourceManager.GetString("RunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Guidance succeeded successfully..
        /// </summary>
        public static string RunSuccessful {
            get {
                return ResourceManager.GetString("RunSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log.
        /// </summary>
        public static string SaveLog {
            get {
                return ResourceManager.GetString("SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process hasn&apos;t finished yet. 
        ///
        ///Are you sure you want to close NuGet Guidance?.
        /// </summary>
        public static string ShutdownDuringExecution {
            get {
                return ResourceManager.GetString("ShutdownDuringExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Recipe &quot;{0}&quot;..
        /// </summary>
        public static string StartingRecipe {
            get {
                return ResourceManager.GetString("StartingRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting NuGet Guidance Execution..
        /// </summary>
        public static string StartUp {
            get {
                return ResourceManager.GetString("StartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue during the initialization of the Guidance.
        ///
        ///Please try again....
        /// </summary>
        public static string StartUpErrorMessage {
            get {
                return ResourceManager.GetString("StartUpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} succeeded..
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un unexpected exception was thrown during the execution of the Guidance..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
